### ISSUE TITLE
Is there an easy way to set a default volume level of 50%?

### ISSUE THREAD

**Issue by JohnnyC1951** [Thibor/jsRapAudio#1]
It is a little annoying to have it default to 100% loudness every time.
I tried but was unable to do it.
It seems it needs to set the volume on firstLoad but the default value in code seems 0 but it plays at 100%.
Any help appreciated.
Even better would be to remember the last used value, permanently.

**Comment by Thibor** [comment]
i added volume in options and changed demo to start with 50% volume
